#!/bin/bash

if [ -z "$NODE_PATH" ]; then
  nodejs_mods="/opt/nodejs/node_modules"
  nodejs18_mods="/opt/nodejs/node18/node_modules"
  runtime_mods="/var/runtime/node_modules"
  task="/var/runtime:/var/task"
  export NODE_PATH="$nodejs18_mods:$nodejs_mods:$runtime_mods:$task"
fi

if [ -n "$FUNCTION_MEMORY_SIZE" ]; then
  new_space=$(expr $FUNCTION_MEMORY_SIZE / 10)
  semi_space=$(expr $new_space / 2)
  old_space=$(expr $FUNCTION_MEMORY_SIZE - $new_space)

  MEMORY_ARGS=("--max-semi-space-size=$semi_space" "--max-old-space-size=$old_space")
fi

# if [ -z "${NODE_EXTRA_CA_CERTS+set}" ]; then
#   # Use the default CA bundle in CN regions and regions that have 3 dashes in their name
#   # /var/runtime/ca-cert.pem contains all certs in "/etc/pki/tls/certs/ca-bundle.crt" that
#   # are not already embedded in the node binary.
#   export NODE_EXTRA_CA_CERTS=/var/runtime/ca-cert.pem
# fi

NODE_ARGS=(
    --expose-gc
    --max-http-header-size 81920
    "${MEMORY_ARGS[@]}"
    /var/runtime/index.mjs $_HANDLER $FUNCTION_DIR
    )

exec /usr/local/bin/node "${NODE_ARGS[@]}"
